# Site settings
title: OBORCHAIN | Blockchain Solutions for One Belt & One Road Menber Countries
description: "Blockchain Solutions for One Belt & One Road Menber Countries"
url: ""
# Build settings
baseurl: ""
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
